// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHCFxXEyTHkYaf_yPonF6UI9DBQUr8mDA',
    appId: '1:302410288884:web:3b892ed28afe0866e458a1',
    messagingSenderId: '302410288884',
    projectId: 'skinspectra',
    authDomain: 'skinspectra.firebaseapp.com',
    storageBucket: 'skinspectra.appspot.com',
    measurementId: 'G-WWDKK6R898',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6AANKbacCM5JwHOcJX4Nx4ut9T_E4Zr0',
    appId: '1:302410288884:android:caae48b11a320557e458a1',
    messagingSenderId: '302410288884',
    projectId: 'skinspectra',
    storageBucket: 'skinspectra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBukiW1f8TrCarlKfMeQVjEX603GhdGbF0',
    appId: '1:302410288884:ios:08ed7854743159ece458a1',
    messagingSenderId: '302410288884',
    projectId: 'skinspectra',
    storageBucket: 'skinspectra.appspot.com',
    iosClientId: '302410288884-il112cq8pegbccoholbvogp903vssgj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinspectra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBukiW1f8TrCarlKfMeQVjEX603GhdGbF0',
    appId: '1:302410288884:ios:f94a8ba6d080636ce458a1',
    messagingSenderId: '302410288884',
    projectId: 'skinspectra',
    storageBucket: 'skinspectra.appspot.com',
    iosClientId: '302410288884-kt5qvudpu3138uavn5g7qlhgucvvhg1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinspectra.RunnerTests',
  );
}
